services:
  login-consent:
    build: .
    container_name: hydra-login-consent
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    networks:
      - desa-shared
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  desa-shared:
    name: desa-shared-network
    external: true